FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Damith Rushika Kothalawala

Polls is a simple API allowing consumers to view polls and vote in them.

## List Components [/components]

### Output [GET]

+ Response 200 (application/json)

        [
            {
            "version":"1.1",
            "components":[
                {
                    "name":"hello.world",
                    "properties":{
                                    "human":{"required":true,"type":"string"}
                                 },
                    "supportedActions":[]
                }
                        ]
            }
        ]

## Get Properties [/components/hello.world]
### Input [POST]
+ Response 200 (application/json)

[
    {
    "platformVersion": "1.1",
    "context": {
        "variables": {}
    },
    "keepTurn": false,
    "transition": true,
    "error": false,
    "modifyContext": false,
    "messages": [
        {
            "tenantId": "1234",
            "channelConversation": {
                "botId": "xyz",
                "sessionId": "1234",
                "type": "test",
                "userId": "1234",
                "channelId": "sample"
            },
            "messagePayload": {
                "type": "text",
                "text": "Greetings Bot Developer"
            }
        },
        {
            "tenantId": "1234",
            "channelConversation": {
                "botId": "xyz",
                "sessionId": "1234",
                "type": "test",
                "userId": "1234",
                "channelId": "sample"
            },
            "messagePayload": {
                "type": "text",
                "text": "Today is Tue Sep 18 2018"
            }
        }
    ]
}
]